### ISSUE TITLE
Native object ownership documentation

### ISSUE THREAD

**Issue by danielperano** [stephengold/jolt-jni#2]
I read the documentation on [handling native object memory](https://github.com/stephengold/jolt-jni?tab=readme-ov-file#freeing-native-objects). One aspect of this that I don't see addressed is the boolean `owner` parameter that gets passed to certain native objects. From inspecting the code, it appears that this mechanism supports multiple Java object instances referencing the same native object instance, but it's not immediately clear how that should be used. I would find it helpful to have a section on this in the documentation.

**Comment by stephengold** [comment]
Thanks for the feedback, @danielperano. I'll give some thought to this aspect. It might be those methods shouldn't be public ;)

**Comment by stephengold** [comment]
@danielperano:

In jolt-jni constructors, the `owner` parameter is a `boolean` that indicates whether the new JVM object will own (be responsible for freeing) its assigned native object. The JVM object's `close()` method will be a no-op if and only if `owner` is `false`.

In general, jolt-jni constructors that accept `owner` should be package-protected. These constructors are internal to jolt-jni, not part of its API. Therefore this information seems to belong in inline comments, not in the project's README.

I grepped the source code and didn't find any `public` or `protected` constructors that accept `boolean owner`. Am I missing something?
