### ISSUE TITLE
Feature Request: TempAllocatorImplWithMallocFallback

### ISSUE THREAD

**Issue by danielperano** [stephengold/jolt-jni#3]
Currently `jolt-jni` exposes `TempAllocatorImpl` and `TempAllocatorMalloc`, but not
[TempAllocatorImplWithMallocFallback](https://jrouwe.github.io/JoltPhysics/class_temp_allocator_impl_with_malloc_fallback.html#a1dde46a11157eaac198e43fb63be9d82). I'd very much prefer using the fixed-size allocator whenever possible, but since this will fail if the size is too small it would be great to have `TempAllocatorImplWithMallocFallback` available.

**Comment by stephengold** [comment]
Added at aff512b.
This addition will appear in the next release.

**Comment by stephengold** [comment]
included in v0.9.1
